services:
  bet_maker:
    tty: true
    build:
      context: .
      dockerfile: bet_maker.Dockerfile
    command:
      - uvicorn bet_maker.app:app --host 0.0.0.0 --port 8001 --reload
    env_file:
      - .evn.example
    volumes:
      - ./bet_maker/:/bet_maker/
    ports:
      - "8001:8001"
    depends_on:
      - postgres


  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5434:5432"
    env_file:
      - .evn.example

volumes:
  postgres_data:
